const Menu = [
    {
        id:1,
        image: "images/1.jpg",
        name:"MAGGI",
        category:"breakfast",
        price: "14Rs.",
        description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Iure, recusandae.",
    },
    {
        id:2,
        image: "images/2.jpg",
        name:"AALOO PAKODA",
        category:"evening",
        price: "30Rs",
        description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Iure, recusandae.",
    },
    {
        id:3,
        image: "images/3.jpg",
        name:"CORN",
        category:"evening",
        price: "30RS.",
        description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Iure, recusandae.",
    },
    {
        id:4,
        image: "images/4.jpg",
        name:"CHOLA BHATURA",
        category:"breakfast",
        price: "35Rs.",
        description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Iure, recusandae.",
    },
    {
        id:5,
        image: "images/5.jpg",
        name:"PIZZA",
        category:"evening",
        price: "90Rs.",
        description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Iure, recusandae.",
    },
    {
        id:6,
        image: "images/6.jpg",
        name:"VEG THALI",
        category:"dinner",
        price: "90Rs.",
        description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Iure, recusandae.",
    },
    {
        id:7,
        image: "images/7.jpg",
        name:"SWEETS",
        category:"dinner",
        price: "50Rs.",
        description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Iure, recusandae.",
    },
    {
        id:8,
        image: "images/8.jpg",
        name:"RAJMA RICE",
        category:"lunch",
        price: "70Rs.",
        description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Iure, recusandae.",
    },
    {
        id:9,
        image: "images/9.jpg",
        name:"SAMOSA",
        category:"evening",
        price: "20Rs.",
        description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Iure, recusandae.",
    },
    {
        id:10,
        image: "images/9.jpg",
        name:"SAMOSA",
        category:"timePass",
        price: "20Rs.",
        description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Iure, recusandae.",
    }
]
export default Menu;